package com.mycompany.trabalhofinal.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;


public class BuscarUsuarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciarUsuarioView
     */
    public BuscarUsuarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbxCampo = new javax.swing.JComboBox<>();
        jTextField = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jBtnNovo = new javax.swing.JButton();
        jBtnVisualizar = new javax.swing.JButton();
        jBtnFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jBtnPermissao = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 248, 248));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gerenciar Usuários");

        jLabel1.setBackground(new java.awt.Color(248, 248, 248));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Buscar por");

        cmbxCampo.setBackground(new java.awt.Color(254, 255, 255));
        cmbxCampo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbxCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nome", "Nome de Usuário" }));

        jBtnBuscar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnBuscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnBuscar.setText("Buscar");

        jBtnNovo.setBackground(new java.awt.Color(248, 248, 248));
        jBtnNovo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnNovo.setText("Novo");

        jBtnVisualizar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnVisualizar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnVisualizar.setText("Visualizar");

        jBtnFechar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnFechar.setText("Fechar");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        jBtnPermissao.setBackground(new java.awt.Color(248, 248, 248));
        jBtnPermissao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnPermissao.setText("Permissões");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbxCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnBuscar))
                            .addComponent(jScrollPane1))
                        .addContainerGap(10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnPermissao)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbxCampo)
                    .addComponent(jBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jBtnVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnPermissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbxCampo;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnPermissao;
    private javax.swing.JButton jBtnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCmbxCampo() {
        return cmbxCampo;
    }

    public JButton getjBtnBuscar() {
        return jBtnBuscar;
    }

    public JButton getjBtnFechar() {
        return jBtnFechar;
    }

    public JButton getjBtnNovo() {
        return jBtnNovo;
    }

    public JButton getjBtnVisualizar() {
        return jBtnVisualizar;
    }

    public JTextField getjTextField() {
        return jTextField;
    }

    public JTable getjTable() {
        return jTable;
    }

    public JButton getjBtnPermissao() {
        return jBtnPermissao;
    }    
    
    
    
    
}
