package com.mycompany.trabalhofinal.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;


public class BuscarUsuarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciarUsuarioView
     */
    public BuscarUsuarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbxCampo = new javax.swing.JComboBox<>();
        jTextField = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jBtnNovo = new javax.swing.JButton();
        jBtnVisualizar = new javax.swing.JButton();
        jBtnFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jExcluir = new javax.swing.JButton();
        jEditar2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 248, 248));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gerenciar Usuários");
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(248, 248, 248));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Buscar por");

        cmbxCampo.setBackground(new java.awt.Color(254, 255, 255));
        cmbxCampo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbxCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nome", "Nome de Usuário" }));

        jBtnBuscar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnBuscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnBuscar.setText("Buscar");

        jBtnNovo.setBackground(new java.awt.Color(248, 248, 248));
        jBtnNovo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnNovo.setText("Novo");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        jBtnVisualizar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnVisualizar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnVisualizar.setText("Visualizar");
        jBtnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVisualizarActionPerformed(evt);
            }
        });

        jBtnFechar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnFechar.setText("Fechar");
        jBtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFecharActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        jExcluir.setBackground(new java.awt.Color(248, 248, 248));
        jExcluir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jExcluir.setText("Excluir");

        jEditar2.setBackground(new java.awt.Color(248, 248, 248));
        jEditar2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jEditar2.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbxCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jBtnNovo)
                        .addGap(56, 56, 56)
                        .addComponent(jBtnVisualizar)
                        .addGap(29, 29, 29)
                        .addComponent(jEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnFechar)
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbxCampo)
                    .addComponent(jBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFecharActionPerformed

    private void jBtnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnVisualizarActionPerformed

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbxCampo;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnVisualizar;
    private javax.swing.JButton jEditar2;
    private javax.swing.JButton jExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCmbxCampo() {
        return cmbxCampo;
    }

    public JButton getjBtnBuscar() {
        return jBtnBuscar;
    }

    public JButton getjBtnFechar() {
        return jBtnFechar;
    }

    public JButton getjBtnNovo() {
        return jBtnNovo;
    }

    public JButton getjBtnVisualizar() {
        return jBtnVisualizar;
    }

    public JTextField getjTextField() {
        return jTextField;
    }

    public JTable getjTable() {
        return jTable;
    }

    public JButton getjEditar2() {
        return jEditar2;
    }



    public JButton getjExcluir() {
        return jExcluir;
    }

    public void setjExcluir(JButton jExcluir) {
        this.jExcluir = jExcluir;
    }
    
    
    
    
}
