package com.mycompany.trabalhofinal.view;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;


public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Trabalho final");
        jDesktopPane = new javax.swing.JDesktopPane();
        lblUsuarioLogado = new javax.swing.JLabel();
        btnNotificacao = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuCadastrar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuBuscar = new javax.swing.JMenuItem();
        jMenuAcao = new javax.swing.JMenu();
        jMenuAlterar1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sofware para acesso a Bancos de Notificações");
        setResizable(false);

        jDesktopPane.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        lblUsuarioLogado.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        btnNotificacao.setBackground(new java.awt.Color(248, 248, 248));
        btnNotificacao.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnNotificacao.setText("Notificações");

        jMenuUsuario.setText("Admin");

        jMenuCadastrar.setText("Cadastrar Usuário");
        jMenuUsuario.add(jMenuCadastrar);
        jMenuUsuario.add(jSeparator1);

        jMenuBuscar.setText("Buscar Usuários");
        jMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuBuscar);

        jMenuBar.add(jMenuUsuario);

        jMenuAcao.setText("Ações");

        jMenuAlterar1.setText("Alterar dados");
        jMenuAcao.add(jMenuAlterar1);

        jMenuBar.add(jMenuAcao);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    public JMenu getjMenuAcao() {
        return jMenuAcao;
    }

    public void setjMenuAcao(JMenu jMenuAcao) {
        this.jMenuAcao = jMenuAcao;
    }

    public JMenuItem getjMenuAlterar1() {
        return jMenuAlterar1;
    }

    public void setjMenuAlterar1(JMenuItem jMenuAlterar1) {
        this.jMenuAlterar1 = jMenuAlterar1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotificacao;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenuAcao;
    private javax.swing.JMenuItem jMenuAlterar1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuBuscar;
    private javax.swing.JMenuItem jMenuCadastrar;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblUsuarioLogado;
    // End of variables declaration//GEN-END:variables
    

    public JDesktopPane getjDesktopPane() {
        return jDesktopPane;
    }

    public JMenuItem getjMenuCadastrar() {
        return jMenuCadastrar;
    }

    public JMenuItem getjMenuBuscar() {
        return jMenuBuscar;
    }

    public JMenu getjMenuUsuario() {
        return jMenuUsuario;
    }

    public JButton getBtnNotificacao() {
        return btnNotificacao;
    }

    public JLabel getLblUsuarioLogado() {
        return lblUsuarioLogado;
    }
    
    
    
}
